// ═══════════════════════════════════════════════════════════════════════════
//  FLEET AI — Master Configuration
//  Auto-generated by setup.sh — edit this file to change settings.
//  Run `bash setup.sh` again to regenerate.
// ═══════════════════════════════════════════════════════════════════════════

export const config = {

  // ── Deployment ────────────────────────────────────────────────────────────
  deployMode:   "local-docker" as const,  // local-docker | local-native | production
  dataMode:     "demo"   as const,  // demo | live
  host:         "192.168.146.109",
  isDev:        true,
  isProduction: false,

  // ── URLs ──────────────────────────────────────────────────────────────────
  urls: {
    backend:    "http://192.168.146.109:3000/api/v1",
    websocket:  "ws://192.168.146.109:3000",
    frontend:   "http://192.168.146.109:5173",
  },

  // ── Ports ─────────────────────────────────────────────────────────────────
  ports: {
    backend:  3000,
    web:      5173,
    grafana:  3001,
    postgres: 5432,
    redis:    6379,
  },

  // ── Database ──────────────────────────────────────────────────────────────
  database: {
    mode:   "docker" as const,         // docker | existing
    url:    process.env.DATABASE_URL ?? "postgresql://fleetai:fleetai@postgres:5432/fleetai",
  },

  // ── Demo seed config ──────────────────────────────────────────────────────
  demo: {
    enabled:       "demo" === "demo",
    vehicleCount:  8,
    driverCount:   5,
    managerEmail:  "manager@bharatlogistics.in",
    managerPass:   "Manager@123",
    driverEmail:   "driver1@bharatlogistics.in",
    driverPass:    "Driver@123",
    orgName:       "Bharat Logistics Pvt. Ltd.",
    orgSlug:       "bharat-logistics",
  },

  // ── Stripe billing (SaaS subscription checkout) ───────────────────────────
  stripe: {
    enabled: false,
    mode: "disabled" as "disabled" | "test" | "live",
    publishableKey: "",
    priceIds: {
      starter: "",
      pro: "",
      enterprise: "",
    },
  },

  // ── Monitoring ────────────────────────────────────────────────────────────
  monitoring: {
    enabled:         true,
    grafanaPort:     3001,
    prometheusPort:  9090,
  },

  // ── Mobile (Expo) ─────────────────────────────────────────────────────────
  mobile: {
    apiUrl:     "http://192.168.146.109:3000/api/v1",
    wsUrl:      "ws://192.168.146.109:3000",
    projectId:  "",
  },

} as const;

export type Config = typeof config;
export default config;
