// ═══════════════════════════════════════════════════════════════════════════
//  FLEET AI — Master Configuration
//
//  This file is the single source of truth for ALL configuration.
//  It is auto-generated by setup.sh but can be edited directly.
//
//  USED BY:
//    • apps/backend  — via process.env (values written to apps/backend/.env)
//    • apps/web      — via import.meta.env (values written to apps/web/.env)
//    • apps/mobile   — via process.env (values written to apps/mobile/.env)
//
//  To regenerate all .env files from this config:
//    bash setup.sh  (choose "skip deploy" at the end)
// ═══════════════════════════════════════════════════════════════════════════

export const config = {

  // ── Deployment ─────────────────────────────────────────────────────────────
  deployMode:    "local-docker" as "local-docker" | "local-native" | "production",
  dataMode:      "demo"         as "demo" | "live",
  host:          "192.168.1.100",         // your machine's LAN IP
  isDev:         true,
  isProduction:  false,

  // ── URLs ───────────────────────────────────────────────────────────────────
  // These are the URLs used by web and mobile to reach the backend.
  // Change `host` above — these are derived automatically by setup.sh.
  urls: {
    backend:   "http://192.168.1.100:3000/api/v1",
    websocket: "ws://192.168.1.100:3000",
    frontend:  "http://192.168.1.100:5173",
  },

  // ── Ports ──────────────────────────────────────────────────────────────────
  ports: {
    backend:   3000,
    web:       5173,
    grafana:   3001,
    postgres:  5432,
    redis:     6379,
  },

  // ── Database ───────────────────────────────────────────────────────────────
  database: {
    // "docker"   → postgres runs in Docker Compose (connection string auto-built)
    // "existing" → supply your own DATABASE_URL
    mode: "docker" as "docker" | "existing",
    url:  process.env.DATABASE_URL ?? "postgresql://fleetai:fleetai_secret@localhost:5432/fleetai",
  },

  // ── Demo Seed Config ───────────────────────────────────────────────────────
  // Only applied when dataMode === "demo"
  demo: {
    enabled:      true,
    vehicleCount: 8,
    driverCount:  5,
    managerEmail: "manager@demo.fleet",
    managerPass:  "Manager123!",
    driverEmail:  "driver1@demo.fleet",   // driver2@, driver3@… also created
    driverPass:   "Driver123!",
    orgName:      "Fleet Demo Co",
    orgSlug:      "fleet-demo",
  },

  // ── Auth ───────────────────────────────────────────────────────────────────
  auth: {
    jwtExpiresIn:        "15m",
    refreshExpiresIn:    "7d",
    // Secrets are kept in .env, not here.
    // setup.sh auto-generates strong secrets on first run.
  },

  // ── AI Provider ────────────────────────────────────────────────────────────
  ai: {
    // "openai"  → requires OPENAI_API_KEY in backend .env
    // "ollama"  → local LLM, no API key needed
    provider:       "ollama" as "openai" | "ollama",
    ollamaBaseUrl:  "http://localhost:11434",
    model:          "llama3",               // ollama model name
    openaiModel:    "gpt-4o-mini",
  },

  // ── Email ──────────────────────────────────────────────────────────────────
  email: {
    // Leave resendApiKey blank → emails print to console in dev mode
    provider:      "resend" as "resend" | "console",
    fromAddress:   "Fleet AI <noreply@fleetai.app>",
  },

  // ── Stripe ─────────────────────────────────────────────────────────────────
  // All keys are injected via .env — configure here for reference only.
  stripe: {
    enabled:  false,   // set true when keys are configured
    plans: {
      starter:    { price: "$49/mo",  maxVehicles: 5,    maxDrivers: 10  },
      pro:        { price: "$149/mo", maxVehicles: 25,   maxDrivers: 50  },
      enterprise: { price: "$499/mo", maxVehicles: 9999, maxDrivers: 9999 },
    },
  },

  // ── Monitoring ─────────────────────────────────────────────────────────────
  monitoring: {
    enabled:          true,
    grafanaPort:      3001,
    prometheusPort:   9090,
    // Grafana credentials set in .env
  },

  // ── Mobile (Expo) ──────────────────────────────────────────────────────────
  mobile: {
    // These are written to apps/mobile/.env as EXPO_PUBLIC_* vars
    apiUrl:    "http://192.168.1.100:3000/api/v1",
    wsUrl:     "ws://192.168.1.100:3000",
    projectId: "",    // Your Expo project ID for push notifications
  },

  // ── CORS ───────────────────────────────────────────────────────────────────
  cors: {
    // These origins are allowed to call the backend API
    origins: [
      "http://192.168.1.100:5173",
      "http://localhost:5173",
      "http://localhost:3000",
    ],
  },

  // ── GPS Batch Writer ───────────────────────────────────────────────────────
  gps: {
    batchSize:         50,    // flush to DB after this many pings
    flushIntervalMs:   2000,  // or every 2 seconds, whichever comes first
    gpsIntervalMs:     3000,  // mobile sends a ping every 3 seconds
  },

} as const;

export type Config = typeof config;
export default config;

// ── Env variable helper (for backend use) ─────────────────────────────────────
// Usage: getEnv("STRIPE_SECRET_KEY") → throws if missing in production
export function getEnv(key: string, fallback?: string): string {
  const val = process.env[key] ?? fallback;
  if (!val && config.isProduction) {
    throw new Error(`Missing required env variable: ${key}`);
  }
  return val ?? "";
}